/**
 * @arthsystems_ Carousel Watcher
 * ================================
 * Watches the Downloads folder for carousel HTML files generated by Claude Chat.
 * Detects the DM keyword in the file content, routes to the correct pin assets folder,
 * and triggers PNG export via Playwright (export-carousel.py).
 *
 * Keyword → folder mapping is read from: scripts/carousel-keywords.json
 * Add new pins there — no need to edit this file.
 *
 * Usage:
 *   npm run watch:carousel        (runs in foreground, Ctrl+C to stop)
 *   node scripts/carousel-watcher.js
 */

'use strict';

const chokidar  = require('chokidar');
const fs        = require('fs');
const path      = require('path');
const { spawnSync } = require('child_process');

// ─── Paths ──────────────────────────────────────────────────────────────────

const DOWNLOADS_DIR  = path.join(process.env.USERPROFILE || process.env.HOME, 'Downloads');
const VAULT_DIR      = path.resolve(__dirname, '..');
const PINS_DIR       = path.join(VAULT_DIR, 'SÍRIOS', '📱 Instagram', '@arthsystems_', '📌 pins');
const KEYWORDS_FILE  = path.join(__dirname, 'carousel-keywords.json');
const EXPORTER       = path.join(__dirname, 'export-carousel.py');

// ─── Keyword map (hot-reloaded from JSON) ────────────────────────────────────

function loadKeywordMap() {
  try {
    return JSON.parse(fs.readFileSync(KEYWORDS_FILE, 'utf-8'));
  } catch {
    console.error(`Could not read ${KEYWORDS_FILE} — using empty map`);
    return {};
  }
}

// ─── Detection ───────────────────────────────────────────────────────────────

function isCarouselFile(filePath) {
  const name = path.basename(filePath).toLowerCase();
  return name.includes('carousel') && name.endsWith('.html');
}

function detectKeyword(html) {
  const keywordMap = loadKeywordMap();
  for (const [keyword, folder] of Object.entries(keywordMap)) {
    if (html.includes(keyword)) return { keyword, folder };
  }
  return null;
}

// ─── Processing ──────────────────────────────────────────────────────────────

function processCarouselFile(filePath) {
  if (!isCarouselFile(filePath)) return;

  const filename = path.basename(filePath);
  console.log(`\n  Detected: ${filename}`);

  let html;
  try {
    html = fs.readFileSync(filePath, 'utf-8');
  } catch (err) {
    console.error(`  Could not read file: ${err.message}`);
    return;
  }

  const match = detectKeyword(html);

  if (!match) {
    console.log(`  WARNING: No DM keyword found in ${filename}`);
    console.log(`  Add the keyword to scripts/carousel-keywords.json and retry.`);
    console.log(`  File left in: ${filePath}`);
    return;
  }

  const destDir  = path.join(PINS_DIR, match.folder);
  const destFile = path.join(destDir, 'carousel_arthsystems.html');

  // Create destination folder
  fs.mkdirSync(destDir, { recursive: true });

  // Copy HTML to pin assets folder
  fs.copyFileSync(filePath, destFile);

  // Remove from Downloads only after successful copy
  try { fs.unlinkSync(filePath); } catch { /* ignore if already moved */ }

  console.log(`  Keyword:  ${match.keyword}`);
  console.log(`  Folder:   ${match.folder}/`);
  console.log(`  Exporting slides...`);

  // Run Playwright exporter
  const result = spawnSync(
    'python',
    ['-X', 'utf8', EXPORTER, '--html', destFile, '--out', destDir],
    { encoding: 'utf-8', stdio: 'inherit' }
  );

  if (result.status === 0) {
    console.log(`\n  All slides ready in: ${match.folder}/`);
    console.log(`  Instagram worker can now publish this carousel.\n`);
  } else {
    console.log(`\n  PNG export failed. Run manually:`);
    console.log(`  python -X utf8 scripts/export-carousel.py --html "${destFile}" --out "${destDir}"\n`);
  }
}

// ─── Watcher ─────────────────────────────────────────────────────────────────

const watcher = chokidar.watch(DOWNLOADS_DIR, {
  persistent:      true,
  ignoreInitial:   true,
  // Wait for file writes to stabilize before firing (critical for large HTML with base64)
  awaitWriteFinish: {
    stabilityThreshold: 2000,
    pollInterval:       500,
  },
  ignored: /(node_modules|\.git)/,
});

watcher
  .on('add',   filePath => processCarouselFile(filePath))
  .on('error', err      => console.error(`Watcher error: ${err}`));

// Print keyword map on startup
const keywordMap = loadKeywordMap();
const keywordList = Object.entries(keywordMap)
  .map(([k, v]) => `${k} → ${v}`)
  .join('\n     ');

console.log(`Carousel Watcher — @arthsystems_`);
console.log(`  Watching: ${DOWNLOADS_DIR}`);
console.log(`  Keywords:`);
console.log(`     ${keywordList}`);
console.log(`\n  Download a carousel from Claude Chat to trigger auto-export.`);
console.log(`  Ctrl+C to stop.\n`);
